M48
; DRILL file {KiCad 9.0.1} date 2025-06-23T00:24:17-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-23T00:24:17-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T6C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T7C1.050
%
G90
G05
T1
X43.7Y21.668
T2
X44.282Y5.63
X50.062Y5.63
T3
X28.982Y2.91
X28.982Y1.11
T4
X87.22Y79.34
T5
X16.472Y2.95
X23.272Y2.95
T6
X64.912Y6.16
X72.892Y6.16
T7
X84.533Y82.027
M30
